name: 'gradle-build'
inputs:
  java-version:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{inputs.java-version}} 
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: ./gradlew build6
